### ISSUE TITLE
Keen to add more comment tag support?

### ISSUE THREAD

**Issue by FlyingOE** [jasraj/q-doc#10]
How keen are you to add more comment tag support, including some of the useful in-line tags?

I've completed the following addition in my own fork:

- `@see` external link support: `/ @see <a href="....">...</a>`
- inline code block support: `{@code ...}` (including the `<code>...</code>` alias)
- inline literal block support: `{@literal ...}` (including the `<tt>...</tt>` alias)
- support for HTML contents in descriptions
- (non-javadoc) one-line k/q code support: `/ q) ....` or `/ k)....`

Please kindly let me know if you are interested these features as additional a pull request.

**Comment by jasraj** [comment]
Hi,

I think they are all excellent additions to the system and would be happy to add them.

Thanks for all the contributions so far; I'm reviewing as fast as I can 😄

**Comment by FlyingOE** [comment]
Bunched up the additional features into #11
