### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by jonnypress** [jasraj/q-doc#14]
Hi Jas

We're having a look at this, looks good and a fit for what we need.  I tried to do a PR for a small change to support macs, but was denied access.  This is the change: 

diff --git a/q-doc.q b/q-doc.q
index 884398d..f5306cb 100644
--- a/q-doc.q
+++ b/q-doc.q
@@ -50,7 +50,7 @@
                :hsym first `$trim system "echo %cd%";
        ];
 
-       if["l"~first string .z.o;
+       if[(first string .z.o) in "lm";
                :hsym first `$trim system "pwd";
        ];
Would you be able to add that? 

Thanks 

Jonny

**Comment by jasraj** [comment]
Hi Jonny,

Thanks for raising the issue - I've just pushed a branch to move q-doc to use the kdb-common libraries (#13).

In this branch, I've removed that function and instead do this:
```
.qdoc.cfg.folderRoot:first ` vs hsym .z.f;
```
Basically using the path of the q-doc.q file. This will work on any OS basically. I'm still testing the other branch but hope to get it merged soon.
