### ISSUE TITLE
Backslash in one line function body 

### ISSUE THREAD

**Issue by derfugu** [jasraj/q-doc#2]
Thanks for the code, I find it very useful. I added an @example tag that parses an example function call. 

I did realize however that the parser can have troubles with certain functions. One such case is backlashes in one line function bodies. 

Example: 
/ backslash in function falls over
/ @param input (String) list of strings
/ @returns (List) of strings, comma appended
f:{[input] : input ,:","};

/ same function, multiline, with backslash in between
/ @param input (String) list of strings
/ @returns (List) of strings, comma appended
h:{
   [input] : input ,:","
   };

h gets parsed correctly, f does not

**Comment by jasraj** [comment]
Thanks for raising this issue! 

My comments:
- Having `};` on a new line without a space used to be unsupported by the q parser. Seems that's fixed now at least on Windows, so I'm making a change to ignore lines that start with `}`.
- In your second example, the parameter list on the second line is not supported (although the parser doesn't break). It should be:

```
h:{[input]
 :input,:",";
};
```
- This lead me to another issue - if there's no description (i.e. only @ tags) then no documentation is generated for that function. ~~I'll raise a separate issue for that~~. #4 
- And finally, the root of the issue you're having is that the first line of the file is being ignored which means the function has no description which is then being ignored by the previous bullet point.

I'll work through these and reply back when they're done.
