### ISSUE TITLE
function with variable, if statement and show

### ISSUE THREAD

**Issue by derfugu** [jasraj/q-doc#3]
Possibly a rather obscure edge case. The last function causes the parsing of the entire file to fail

/ return true if true is true, no params
/ works
g:{ if[1b=1b;:1b };

/ show true if true is true, no params
/ works
k:{if[1b=1b; show "true"]};

/ return true if true is true, params
/ works
l:{[]if[1b=1b;:1b]};

/ show true if true is true - this one fails the whole file
/ fails
/j:{[] if[1b=1b; show "true"]};

**Comment by derfugu** [comment]
and again, this is only an issue if the function body is on the same line, seems like a good rule of thumb to separate it out

**Comment by jasraj** [comment]
Please try this one again with the new changes I just committed. It seems to work OK now.
