### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by chenkangcrack** [jasraj/q-doc#6]
if the backspace between the return type and description words is less than 2, the first description word will never show, as below,if the backspace between right bracket of returnType  and the word "**_Return_**" is less than 2, the word  "**_Return_**" will never show
<img width="251" alt="capture" src="https://cloud.githubusercontent.com/assets/11851538/24031727/2f8da35a-0b1f-11e7-881a-c5ff916e7df1.PNG">

**Comment by FlyingOE** [comment]
Fixed by #7

**Comment by jasraj** [comment]
Will review #7
